// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var _this = this;
    this.url = "";
    this.name = "";
    return $("button").on("click", function() {
      chrome.tabs.getSelected(window.id, function(tab) {
        _this.url = tab.url;
        return $(".url").text(_this.url);
      });
      $(".status").text("crawling");
      $.get("https://github.com/notifications", function(data) {
        _this.name = $(data).find("#user-links .name").text();
        return $(".name").text(_this.name);
      });
      console.log("test");
      console.log(_this.name);
      console.log(_this.url);
      return $.ajax({
        url: "http://codingstar.herokuapp.com/stars.json",
        type: "post",
        data: {
          user: "test",
          url: "test"
        }
      }).done(function(data) {
        return $(".status").text("done!");
      }).always(function() {
        return $(".status").text("sending..");
      });
    });
  });

}).call(this);
